# Generated by Django 3.2.18 on 2023-02-27 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Berita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_berita', models.CharField(max_length=255)),
                ('isi_berita', models.TextField()),
                ('penulis', models.CharField(default='authors', max_length=20)),
                ('kategori', models.CharField(max_length=20)),
                ('waktu_post', models.DateTimeField(auto_now_add=True)),
                ('waktu_edit', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(editable=False, max_length=255)),
            ],
        ),
    ]
