# Generated by Django 3.2.18 on 2023-03-04 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='berita',
            options={'ordering': ['-waktu_post']},
        ),
    ]
